---
dependencies:
  cupertino_icons: ^1.0.2
  email_auth: ^1.0.0
  environment_config: ^3.1.0
  firebase_auth: ^3.3.10
  firebase_core: ^1.10.6
  firebase_database: ^9.0.8
  firebase_messaging: ^11.4.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.6.1
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.1
  group_radio_button: ^1.2.0
  intl: ^0.17.0
  logger: ^1.1.0
  page_transition: ^2.0.5
  regexpattern: ^2.0.1
  timeline_tile: ^2.0.0
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.17.0-182.0.dev <3.0.0'
flutter:
  assets:
    - assets/
  uses-material-design: true
name: student_record_bus
publish_to: none
version: 1.0.0+1